/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Chat;


import LogIn.*;
import Utilerias.ImageFromMongoDBRenderer;
import Utilerias.ImageRenderer;
import Utilerias.JButtonCellEditor;
import Utilerias.JButtonRenderer;
import excepcion.ExcepcionPresentacion;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import negocio.JANegocio;


/**
 *
 * @author santi
 */
public class frmChat extends javax.swing.JFrame {

    private DefaultTableModel modeloTabla;
    private JANegocio negocio;
    
    /**
     * Creates new form LogIn
     */
    public frmChat(JANegocio negocio) {
        initComponents();
        //inicializarTabla();
        this.setLocationRelativeTo(this);
        this.setSize(700, 520);
        this.negocio = negocio;

    }
 
   // Método para inicializar la tabla
    /*private void inicializarTabla() {
        // Inicializar la tabla y el modelo de tabla
        tblChat = new JTable();
        modeloTabla = new DefaultTableModel();

        // Configurar el modelo de tabla
        tblChat.setModel(modeloTabla);

        // Agregar columnas al modelo de tabla
        modeloTabla.addColumn("Nombre"); // Supongamos que la columna 0 es el nombre del usuario

        // Llenar la tabla con datos de ejemplo (aquí deberías cargar los datos desde tu base de datos)
        Object[] datosFila1 = {"Usuario 1"};
        Object[] datosFila2 = {"Usuario 2"};
        modeloTabla.addRow(datosFila1);
        modeloTabla.addRow(datosFila2);

        // Configurar el renderizador de imágenes para la columna específica
        int indiceColumnaImagen = 1; // Suponiendo que la columna 1 es donde quieres mostrar la imagen
        tblChat.getColumnModel().getColumn(indiceColumnaImagen).setCellRenderer(new ImageFromMongoDBRenderer());
        
        // Agregar la tabla al contenedor de la ventana (si es necesario)
        JScrollPane scrollPane = new JScrollPane(tblChat);
        getContentPane().add(scrollPane); // Asumiendo que la ventana es un contenedor de tipo JFrame o similar
    }*/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        fldMensaje = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fldFoto = new javax.swing.JTextField();
        btnPerfil = new javax.swing.JButton();
        btnContactos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnEncontrarImagen = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChat = new javax.swing.JTable();
        btnEnviarMensaje = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.setBackground(new java.awt.Color(153, 230, 153));

        btnCerrar.setBackground(Color.red);
        btnCerrar.setText("X");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Color customColor = new Color(35, 135, 35);
        Border lineBorder = BorderFactory.createLineBorder(customColor, 2);
        fldMensaje.setBorder(lineBorder);
        fldMensaje.setBackground(new java.awt.Color(186, 219, 186));
        fldMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldMensajeActionPerformed(evt);
            }
        });
        jPanel1.add(fldMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 450, 30));

        jLabel2.setText("Foto");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 180, 20));

        fldFoto.setBorder(lineBorder);
        fldFoto.setBackground(new java.awt.Color(186, 219, 186));
        fldFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldFotoActionPerformed(evt);
            }
        });
        jPanel1.add(fldFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 350, 30));

        btnPerfil.setBorder(lineBorder);
        btnPerfil.setBackground(new java.awt.Color(66, 143, 66));
        btnPerfil.setText("Ver Perfil");
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });
        jPanel1.add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 110, 30));

        btnContactos.setBorder(lineBorder);
        btnContactos.setBackground(new java.awt.Color(66, 143, 66));
        btnContactos.setText("Ver Contactos");
        btnContactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactosActionPerformed(evt);
            }
        });
        jPanel1.add(btnContactos, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 110, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Chats");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, 20));

        Color customColor1 = new Color(0, 113, 219);
        Color customColor4 = new Color(78, 160, 237);
        Border lineBorder3 = BorderFactory.createLineBorder(customColor1, 2);
        btnEncontrarImagen.setBorder(lineBorder3);
        btnEncontrarImagen.setBackground(customColor4);
        btnEncontrarImagen.setText("Encontrar imagen");
        btnEncontrarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncontrarImagenActionPerformed(evt);
            }
        });
        jPanel1.add(btnEncontrarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 680, 160, 40));

        jLabel4.setText("Mensaje *");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 180, 20));

        tblChat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Imagen"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblChat);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        Color customColor2 = new Color(0, 113, 219);
        Color customColor3 = new Color(78, 160, 237);
        Border lineBorder2 = BorderFactory.createLineBorder(customColor2, 2);
        btnEncontrarImagen.setBorder(lineBorder2);
        btnEncontrarImagen.setBackground(customColor3);
        btnEnviarMensaje.setText("Enviar");
        btnEnviarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarMensajeActionPerformed(evt);
            }
        });
        jPanel1.add(btnEnviarMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 680, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fldFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldFotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldFotoActionPerformed

    private void fldMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldMensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldMensajeActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        frmMainMenu frm = new frmMainMenu(negocio);
        frm.show();
        this.dispose();           
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContactosActionPerformed

    private void btnEncontrarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncontrarImagenActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();

        // Show the open dialog
        int result = fileChooser.showOpenDialog(this);

        // Check if a file was selected
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            fldFoto.setText(selectedFile.getAbsolutePath());
        }

    }//GEN-LAST:event_btnEncontrarImagenActionPerformed

    private void btnEnviarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarMensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarMensajeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnContactos;
    private javax.swing.JButton btnEncontrarImagen;
    private javax.swing.JButton btnEnviarMensaje;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JTextField fldFoto;
    private javax.swing.JTextField fldMensaje;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblChat;
    // End of variables declaration//GEN-END:variables
}
