/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Chat;


import LogIn.*;
import Utilerias.ImageRenderer;
import Utilerias.JButtonCellEditor;
import Utilerias.JButtonRenderer;
import excepcion.ExcepcionPresentacion;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.border.Border;
import javax.swing.table.TableColumnModel;
import negocio.JANegocio;


/**
 *
 * @author santi
 */
public class frmChat extends javax.swing.JFrame {

    JANegocio negocio;
    
    /**
     * Creates new form LogIn
     */
    public frmChat(JANegocio negocio) {
        initComponents();
        cargarConfiguracionInicialTablaChats();
        cargarConfiguracionInicialTablaMiPerfil();
        this.setLocationRelativeTo(this);
        this.negocio = negocio;

    }

    private void cargarConfiguracionInicialTablaChats() { 
           
        TableColumnModel modeloColumnas = this.tblChats.getColumnModel();


        
        ActionListener onAprobarClickListener = new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                
            }               
        };
        int indiceColumnaEditar = 0;
        Color color = new Color(178, 218, 250);
        modeloColumnas.getColumn(indiceColumnaEditar).setCellRenderer(new JButtonRenderer("Nombre",color));
        modeloColumnas.getColumn(indiceColumnaEditar).setCellEditor(new JButtonCellEditor("Nombre", onAprobarClickListener));


        tblChats.getColumnModel().getColumn(1).setCellRenderer(new ImageRenderer("placeholder.jpg"));
       
    }         
    
    private void cargarConfiguracionInicialTablaMiPerfil() { 
        tblMiFoto.setRowHeight(0, 50);   
        tblMiFoto.getColumnModel().getColumn(0).setCellRenderer(new ImageRenderer("placeholder.jpg"));
       
    }         
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        fldMensaje = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fldFoto = new javax.swing.JTextField();
        btnPerfil = new javax.swing.JButton();
        btnContactos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnEncontrarImagen = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChats = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblChat = new javax.swing.JTable();
        btnEnviarMensaje = new javax.swing.JButton();
        btnNuevoChat = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMiFoto = new javax.swing.JTable();
        btnDetalles = new javax.swing.JButton();
        btnAgregarContactos = new javax.swing.JButton();
        btnDetalles2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.setBackground(new java.awt.Color(153, 230, 153));

        btnCerrar.setBackground(Color.red);
        btnCerrar.setText("X");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Color customColor = new Color(35, 135, 35);
        Border lineBorder = BorderFactory.createLineBorder(customColor, 2);
        fldMensaje.setBorder(lineBorder);
        fldMensaje.setBackground(new java.awt.Color(186, 219, 186));
        fldMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldMensajeActionPerformed(evt);
            }
        });
        jPanel1.add(fldMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 700, 350, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel2.setText("Foto");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 730, 180, 20));

        fldFoto.setBorder(lineBorder);
        fldFoto.setBackground(new java.awt.Color(186, 219, 186));
        fldFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldFotoActionPerformed(evt);
            }
        });
        jPanel1.add(fldFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 750, 350, 30));

        btnPerfil.setBorder(lineBorder);
        btnPerfil.setBackground(new java.awt.Color(66, 143, 66));
        btnPerfil.setText("Ver Perfil");
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });
        jPanel1.add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, 110, 30));

        btnContactos.setBorder(lineBorder);
        btnContactos.setBackground(new java.awt.Color(66, 143, 66));
        btnContactos.setText("Ver Contactos");
        btnContactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactosActionPerformed(evt);
            }
        });
        jPanel1.add(btnContactos, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 110, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Chats");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, 20));

        Color customColor2 = new Color(0, 113, 219);
        Color customColor3 = new Color(78, 160, 237);
        Border lineBorder2 = BorderFactory.createLineBorder(customColor2, 2);
        btnEncontrarImagen.setBorder(lineBorder2);
        btnEncontrarImagen.setBackground(customColor3);
        btnEncontrarImagen.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        btnEncontrarImagen.setText("Encontrar Imagen");
        btnEncontrarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncontrarImagenActionPerformed(evt);
            }
        });
        jPanel1.add(btnEncontrarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 790, 110, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel4.setText("Mensaje *");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 680, 180, 20));

        tblChats.setAutoCreateRowSorter(true);
        tblChats.setBackground(new java.awt.Color(66, 143, 66));
        tblChats.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 143, 66)));
        tblChats.setForeground(new java.awt.Color(51, 153, 0));
        tblChats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Foto "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChats.setToolTipText("");
        tblChats.setSelectionForeground(new java.awt.Color(66, 143, 66));
        jScrollPane1.setViewportView(tblChats);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 240, 710));

        tblChat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mensaje", "Foto", "Fecha", "Enviado por"
            }
        ));
        jScrollPane2.setViewportView(tblChat);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 590, 580));

        btnEnviarMensaje.setBorder(lineBorder);
        btnEnviarMensaje.setBackground(new java.awt.Color(66, 143, 66));
        btnEnviarMensaje.setText("Enviar Mensaje");
        btnEnviarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarMensajeActionPerformed(evt);
            }
        });
        jPanel1.add(btnEnviarMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 700, 230, 80));

        btnNuevoChat.setBorder(lineBorder);
        btnNuevoChat.setBackground(new java.awt.Color(66, 143, 66));
        btnNuevoChat.setText("Nuevo chat");
        btnNuevoChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoChatActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevoChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 140, 30));

        tblMiFoto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Mi foto de perfil"
            }
        ));
        jScrollPane3.setViewportView(tblMiFoto);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 140, 70));

        btnDetalles.setBorder(lineBorder);
        btnDetalles.setBackground(new java.awt.Color(66, 143, 66));
        btnDetalles.setText("Ver Detalles");
        btnDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetallesActionPerformed(evt);
            }
        });
        jPanel1.add(btnDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 160, 30));

        btnAgregarContactos.setBorder(lineBorder);
        btnAgregarContactos.setBackground(new java.awt.Color(66, 143, 66));
        btnAgregarContactos.setText("Agregar contactos");
        btnAgregarContactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarContactosActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarContactos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 140, 30));

        btnDetalles2.setBorder(lineBorder);
        btnDetalles2.setBackground(new java.awt.Color(66, 143, 66));
        btnDetalles2.setText("Agregar Integrantes");
        btnDetalles2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalles2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnDetalles2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 160, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fldFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldFotoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fldFotoActionPerformed

    private void fldMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldMensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldMensajeActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        frmMainMenu frm = new frmMainMenu(negocio);
        frm.show();
        this.dispose();           
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        // TODO add your handling code here:
        frmPerfil frm = new frmPerfil(negocio);
        frm.show();
        this.dispose();
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactosActionPerformed
        // TODO add your handling code here:
        frmVerContactos frm = new frmVerContactos(negocio);
        frm.show();
        this.dispose();
    }//GEN-LAST:event_btnContactosActionPerformed

    private void btnEncontrarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncontrarImagenActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();

        // Show the open dialog
        int result = fileChooser.showOpenDialog(this);

        // Check if a file was selected
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            fldFoto.setText(selectedFile.getAbsolutePath());
        }

    }//GEN-LAST:event_btnEncontrarImagenActionPerformed

    private void btnEnviarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarMensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarMensajeActionPerformed

    private void btnNuevoChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoChatActionPerformed
        // TODO add your handling code here:
        frmNuevoChat frm = new frmNuevoChat(negocio);
        frm.show();
        this.dispose();
    }//GEN-LAST:event_btnNuevoChatActionPerformed

    private void btnDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetallesActionPerformed

    private void btnAgregarContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarContactosActionPerformed
        // TODO add your handling code here:
        frmAgregarContactos frm = new frmAgregarContactos(negocio);
        frm.show();
        this.dispose();        
    }//GEN-LAST:event_btnAgregarContactosActionPerformed

    private void btnDetalles2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalles2ActionPerformed
        // TODO add your handling code here:
        frmAgregarIntegrantes frm = new frmAgregarIntegrantes(negocio);
        frm.show();
        this.dispose(); 
    }//GEN-LAST:event_btnDetalles2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarContactos;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnContactos;
    private javax.swing.JButton btnDetalles;
    private javax.swing.JButton btnDetalles2;
    private javax.swing.JButton btnEncontrarImagen;
    private javax.swing.JButton btnEnviarMensaje;
    private javax.swing.JButton btnNuevoChat;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JTextField fldFoto;
    private javax.swing.JTextField fldMensaje;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblChat;
    private javax.swing.JTable tblChats;
    private javax.swing.JTable tblMiFoto;
    // End of variables declaration//GEN-END:variables
}
