/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Chat;

import DTO.UsuarioDTO;
import DocsDTO.DireccionDTO;
import LogIn.*;
import Negocio.ChatNegocio;
import java.awt.Color;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.border.Border;
import Negocio.UsuarioNegocio;
import excepciones.NegocioException;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author santi
 */
public class frmPerfil extends javax.swing.JFrame {

    UsuarioNegocio usuarioNegocio;
    ChatNegocio chatNegocio;
    UsuarioDTO u;

    /**
     * Creates new form LogIn
     */
    public frmPerfil(UsuarioNegocio usuarioNegocio, ChatNegocio chatNegocio, UsuarioDTO u) {
        initComponents();
        this.setLocationRelativeTo(this);
        this.usuarioNegocio = usuarioNegocio;
        this.chatNegocio = chatNegocio;
        this.u = u;
        llenarFields();

    }

    public byte[] convertirImagenABytes(File file) throws IOException {
        // Leer el archivo de imagen en un InputStream
        InputStream inputStream = new FileInputStream(file);
        byte[] bytes = inputStream.readAllBytes();
        inputStream.close();
        return bytes;
    }    
    
    public void llenarFields(){
    
        this.fldContraseña.setText(u.getContraseña());
        this.fldColonia2.setText(u.getDireccion().getCodigoPostal());
        this.fldCalle.setText(u.getDireccion().getCalle());
        this.fldNumero.setText(u.getDireccion().getNumero());
        this.fldTelefono.setText(u.getTelefono());
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        fldTelefono = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fldImagen = new javax.swing.JTextField();
        fldContraseña = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnEncontrarImagen = new javax.swing.JButton();
        fldNumero = new javax.swing.JTextField();
        fldCalle = new javax.swing.JTextField();
        fldColonia2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.setBackground(new java.awt.Color(153, 230, 153));

        Color customColor = new Color(35, 135, 35);
        Border lineBorder = BorderFactory.createLineBorder(customColor, 2);
        Color customColor2 = new Color(0, 113, 219);
        Color customColor3 = new Color(78, 160, 237);
        Border lineBorder2 = BorderFactory.createLineBorder(customColor2, 2);
        btnGuardar.setBorder(lineBorder2);
        btnGuardar.setBackground(customColor3);
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnGuardar.setText("Editar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 180, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 64)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        btnCerrar.setBackground(Color.red);
        btnCerrar.setText("X");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        fldTelefono.setBorder(lineBorder);
        fldTelefono.setBackground(new java.awt.Color(186, 219, 186));
        fldTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(fldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 230, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Teléfono *");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 230, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Imagen de Perfil *");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 230, -1));

        fldImagen.setBorder(lineBorder);
        fldImagen.setBackground(new java.awt.Color(186, 219, 186));
        fldImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldImagenActionPerformed(evt);
            }
        });
        jPanel1.add(fldImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 230, 40));

        fldContraseña.setBorder(lineBorder);
        fldContraseña.setBackground(new java.awt.Color(186, 219, 186));
        fldContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(fldContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 230, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Dirección completa *");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 230, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Contraseña *");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 230, -1));

        btnEncontrarImagen.setBorder(lineBorder2);
        btnEncontrarImagen.setBackground(customColor3);
        btnEncontrarImagen.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        btnEncontrarImagen.setText("Encontrar Imagen");
        btnEncontrarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncontrarImagenActionPerformed(evt);
            }
        });
        jPanel1.add(btnEncontrarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 110, 20));

        fldNumero.setBorder(lineBorder);
        fldNumero.setBackground(new java.awt.Color(186, 219, 186));
        fldNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldNumeroActionPerformed(evt);
            }
        });
        jPanel1.add(fldNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 230, 40));

        fldCalle.setBorder(lineBorder);
        fldCalle.setBackground(new java.awt.Color(186, 219, 186));
        fldCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldCalleActionPerformed(evt);
            }
        });
        jPanel1.add(fldCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 230, 40));

        fldColonia2.setBorder(lineBorder);
        fldColonia2.setBackground(new java.awt.Color(186, 219, 186));
        fldColonia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldColonia2ActionPerformed(evt);
            }
        });
        jPanel1.add(fldColonia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 230, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:



        // Crear un objeto UsuarioDTO con los datos del formulario
        UsuarioDTO usuario = new UsuarioDTO();
        usuario.setId(u.getId());
        usuario.setNombre(u.getNombre());
        usuario.setApellidoPaterno(u.getApellidoPaterno());
        usuario.setApellidoMaterno(u.getApellidoMaterno());
        DireccionDTO direccion = new DireccionDTO(fldCalle.getText().trim(), fldNumero.getText().trim(), fldColonia2.getText().trim());
        usuario.setDireccion(direccion);
        usuario.setTelefono(fldTelefono.getText().trim());
        usuario.setContraseña(fldContraseña.getText().trim());
        usuario.setSexo(u.getSexo());
        usuario.setFechaNacimiento(u.getFechaNacimiento());

        // Convertir la imagen a byte[]
        try
        {
            byte[] imagenBytes = convertirImagenABytes(new File(fldImagen.getText()));
            if (imagenBytes != null){
            usuario.setImagenPerfil(imagenBytes);
            }
            else
            usuario.setImagenPerfil(u.getImagenPerfil());
            System.out.println(imagenBytes);
        } catch (IOException ex)
        {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al convertir la imagen a bytes.");
            return;
        }

        try {
            // Llamar al método del negocio para crear el usuario en la base de datos
            
            usuarioNegocio.actualizarUsuario(usuario);
            
            this.u = usuarioNegocio.obtenerUsuarioPorId(usuario.getId());
        } catch (NegocioException ex) {
            Logger.getLogger(frmRegistrar.class.getName()).log(Level.SEVERE, null, ex);
        }
            JOptionPane.showMessageDialog(this, "Usuario creado exitosamente.");



    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        frmChat frm = new frmChat(usuarioNegocio, chatNegocio, u);
        frm.show();
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void fldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldTelefonoActionPerformed

    private void fldContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldContraseñaActionPerformed

    private void fldImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldImagenActionPerformed

    private void btnEncontrarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncontrarImagenActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();

        // Show the open dialog
        int result = fileChooser.showOpenDialog(this);

        // Check if a file was selected
        if (result == JFileChooser.APPROVE_OPTION)
        {
            File selectedFile = fileChooser.getSelectedFile();
            fldImagen.setText(selectedFile.getAbsolutePath());
        }


    }//GEN-LAST:event_btnEncontrarImagenActionPerformed

    private void fldNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldNumeroActionPerformed

    private void fldCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldCalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldCalleActionPerformed

    private void fldColonia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldColonia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldColonia2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEncontrarImagen;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField fldCalle;
    private javax.swing.JTextField fldColonia;
    private javax.swing.JTextField fldColonia1;
    private javax.swing.JTextField fldColonia2;
    private javax.swing.JTextField fldContraseña;
    private javax.swing.JTextField fldImagen;
    private javax.swing.JTextField fldNumero;
    private javax.swing.JTextField fldTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
